# Generated by Django 5.1.7 on 2025-04-05 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsdata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='battery_level',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='engine_status',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='ignition_on',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='max_speed',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='speed_kmh',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='latitude',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='longitude',
            field=models.JSONField(default=list),
        ),
    ]
