# Generated by Django 5.0.7 on 2025-02-24 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kovais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(blank=True, null=True, unique=True)),
                ('status', models.CharField(blank=True, default='Available', max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='spaorder',
            old_name='order_type',
            new_name='status',
        ),
        migrations.AddField(
            model_name='gymorder',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kovais.employee'),
        ),
        migrations.AddField(
            model_name='hotelorder',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kovais.employee'),
        ),
        migrations.AddField(
            model_name='saloonorder',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kovais.employee'),
        ),
        migrations.AddField(
            model_name='spaorder',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kovais.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hotelorder',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kovais.userdetails'),
        ),
        migrations.RemoveField(
            model_name='hotelorder',
            name='room_count',
        ),
        migrations.AlterField(
            model_name='hotelorder',
            name='status',
            field=models.CharField(blank=True, default='Available', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saloonorder',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kovais.userdetails'),
        ),
        migrations.AlterField(
            model_name='spaorder',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kovais.userdetails'),
        ),
        migrations.AddField(
            model_name='hotelorder',
            name='room_count',
            field=models.ManyToManyField(blank=True, to='Kovais.rooms'),
        ),
    ]
