# Generated by Django 5.0.7 on 2025-02-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kovais', '0002_rooms_rename_order_type_spaorder_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelorder',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='hotelorder',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
