# Generated by Django 5.1.7 on 2025-03-21 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='LocationExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('india', 'India'), ('usa', 'USA')], default='india', max_length=20)),
                ('state', models.CharField(choices=[('tamil_nadu', 'Tamil Nadu'), ('karnataka', 'Karnataka'), ('maharashtra', 'Maharashtra'), ('california', 'California'), ('texas', 'Texas'), ('new_york', 'New York')], default='tamil_nadu', max_length=20)),
                ('district', models.CharField(choices=[('chennai', 'Chennai'), ('madurai', 'Madurai'), ('bangalore', 'Bangalore'), ('mysore', 'Mysore'), ('mumbai', 'Mumbai'), ('pune', 'Pune'), ('los_angeles', 'Los Angeles'), ('san_francisco', 'San Francisco'), ('houston', 'Houston'), ('dallas', 'Dallas'), ('manhattan', 'Manhattan'), ('brooklyn', 'Brooklyn')], default='chennai', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LandListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='land_images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('detail_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='app.locationexample')),
            ],
        ),
    ]
