# Generated by Django 5.1.7 on 2025-04-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(blank=True, choices=[('shopkeeper', 'Shopkeeper'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
