# Generated by Django 5.1.7 on 2025-04-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ecomapp', '0002_alter_customer_email_alter_customer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.customer'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='shopkeeper',
            field=models.ForeignKey(help_text='Shopkeeper who owns the banner', on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='ecomapp.customer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='ecom_employees', related_query_name='ecom_employee', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='ecom_employees', related_query_name='ecom_employee', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.customer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.customer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employee',
            field=models.ForeignKey(help_text='Shop owner (employee)', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.customer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.customer'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.customer'),
        ),
    ]
