# Generated by Django 5.0.7 on 2025-01-30 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savejson',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_utility.plan'),
        ),
    ]
