# Generated by Django 5.0.4 on 2024-05-07 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_utility', '0007_videoupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='video_frames/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_utility.videoupload')),
            ],
        ),
    ]
