# Generated by Django 5.0.4 on 2024-05-11 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_utility', '0008_videoframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_utility.itemlist'),
        ),
    ]
