# Generated by Django 5.0.4 on 2024-05-23 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_utility', '0010_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoframe',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
