# Generated by Django 5.0.6 on 2024-06-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_utility', '0012_marker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='distance_to_next_marker',
            new_name='distance',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='distance_to_previous_marker',
        ),
    ]
