# Generated by Django 5.0.6 on 2024-06-30 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_utility', '0014_alter_videoupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_utility.plan'),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
