# Generated by Django 5.0.6 on 2024-07-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_utility', '0015_videoupload_plan_alter_videoupload_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email_id', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.CharField(blank=True, choices=[('React Development', 'React Development'), ('React Native Development', 'React Native Development'), ('Android Java Development', 'Android Java Development'), ('PHP Laravel Development', 'PHP Laravel Development'), ('Python Django Development', 'Python Django Development')], max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='uploads/Resume')),
            ],
        ),
    ]
