# Generated by Django 5.0.6 on 2024-08-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_utility', '0016_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoframe',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_utility.plan'),
        ),
    ]
