# Generated by Django 5.0.6 on 2024-10-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_utility', '0017_videoframe_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
