# Generated by Django 5.0.6 on 2024-10-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_utility', '0018_savejson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savejson',
            old_name='store_data',
            new_name='data',
        ),
    ]
