# Generated by Django 5.0.6 on 2024-10-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_utility', '0019_rename_store_data_savejson_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='savejson',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
