# Generated by Django 5.0.7 on 2025-02-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kovais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelorder',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='hotelorder',
            old_name='employee',
            new_name='employee_id',
        ),
    ]
