# Generated by Django 5.0.7 on 2025-02-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kovais', '0002_rename_customer_hotelorder_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelorder',
            name='room_count',
        ),
        migrations.AddField(
            model_name='hotelorder',
            name='room_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
