# Generated by Django 5.1.7 on 2025-03-21 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kovais', '0003_remove_hotelorder_room_count_hotelorder_room_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, default='pending', max_length=255, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kovais.employee')),
            ],
        ),
    ]
