# Generated by Django 5.1.7 on 2025-03-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kovais', '0004_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saloonorder',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='saloonorder',
            name='services',
        ),
        migrations.AddField(
            model_name='saloonorder',
            name='service_descriptions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='saloonorder',
            name='service_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='saloonorder',
            name='service_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saloonorder',
            name='service_status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='emblem_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saloonorder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saloonorder',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='saloonorder',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='saloonorder',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
