"""
Django settings for building_construction project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# BASE_DIR = Path(__file__).resolve().parent.parent
# STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!

# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '2026-103-175-108-130.ngrok-free.app']

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qy99_@e#dcu^cbt$=dazit$_*)5yz*)f_6cmkpxu9r-a9)iq90'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = True


ALLOWED_HOSTS = ['localhost', '127.0.0.1','api.capture360.ai', '192.168.1.55','192.168.1.36','59.97.51.97','192.168.1.33','3379-59-97-51-97.ngrok-free.app','capture360.ai','www.capture360.9ai','192.168.1.37','f158-2401-4900-9269-fea8-f59e-45e7-eb42-7a6c.ngrok-free.app','localhost:5173','1df7-2409-40f4-204e-df45-2595-c282-9df8-4a09.ngrok-free.app']


CORS_ALLOW_HEADERS = [
    'Accept',
    'Accept-Encoding',
    'Accept-Language',
    'Connection',
    'Content-Length',
    'Content-Type',
    'Host',
    'Origin',
    'Referer',
    'User-Agent',
    'ngrok-skip-browser-warning',
    'strict-origin-when-cross-origin',
    # Add other allowed headers if needed
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'https://1df7-2409-40f4-204e-df45-2595-c282-9df8-4a09.ngrok-free.app',
    'http://localhost:5173',
    'http://192.168.1.33:8080',
    'https://api.capture360.ai',
    'http://api.capture360.ai',
    'https://9646-106-219-181-170.ngrok-free.app',                    
    'http://localhost:3000',
    'http://localhost:3001',
    'http://localhost:3002',
    'http://localhost:3003',
    'http://localhost:3004',
    'http://localhost:8090',
    'https://thiran360ai.github.io',  # Corrected
    'http://127.0.0.1',
    'http://127.0.0.1:8080',
    'https://gokulrajalp.github.io',
    'http://192.168.1.3',
    'https://capture360.ai',
    'http://capture360.ai',
    'https://www.capture360.ai',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]


CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins to simplify CORS configuration

LOGIN_REDIRECT_URL = '/dashboard/'  # Redirect users after login
APPEND_SLASH = False

# import os
# os.environ["officeapp"] = "/opt/homebrew/lib/libgdal.dylib"



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'profile_utility',
    'Kovais',
    'import_export',
    'corsheaders',
    'ecomapp',
    'app',
    'bike',
    'Attendance',
    'officeapp',
    'gateway',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'building_construction.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'building_construction.wsgi.application'
# AUTH_USER_MODEL = 'bike.UserProfile'  # Replace 'yourapp' with your actual app name
# AUTH_USER_MODEL = 'ecomapp.Customer'  # Replace 'yourapp' with your actual app name


# Defining variables for user models
BIKE_USER_MODEL = 'bike.UserProfile'
ECOM_USER_MODEL = 'ecomapp.Customer'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

from decouple import config

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.mysql'),
        'NAME': config('DB_NAME', default=''),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', cast=int, default=3306),
        'CONN_MAX_AGE': 600,
        'POOL_OPTIONS': {
            'MAX_CONNECTIONS': 100,  # Max connections per thread
            'CONN_TIMEOUT': 60,  # 1 minute timeout
        },
    }
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "manikvasu2000@gmail.com"
EMAIL_HOST_PASSWORD = "kqns jikr eoep yioj"
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "manikvasu2000@gmail.com"

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
# }
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR)

# STATIC_URL = 'static/'
# STATIC_URL = 'static/'
#MEDIA_ROOT=os.path.join(BASE_DIR,'image')
# MEDIA_URL='/images/'
# MEDIA_ROOT=BASE_DIR/'static'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR)

STATIC_URL = 'static/'
STATIC_URL = 'static/'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Remove or comment out this line if not needed
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # Add this if missing

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# INTERNAL_IPS = ['127.0.0.1'] django debug toolbar
INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis broker

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
