# Generated by Django 5.0.7 on 2025-02-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
